language: node_js
node_js:
  - 6.2.2
notifications:
  - felipempantoja@gmail.com
before_install:
  - npm install -g bower
  - npm install grunt --save-dev
  - npm install -g grunt-cli
  - npm install grunt-contrib-copy grunt-contrib-clean grunt-contrib-concat grunt-contrib-uglify grunt-contrib-cssmin grunt-usemin grunt-ng-annotate --save-dev
  - npm install karma --save-dev
  - npm install -g karma-cli
  - npm install -g protractor
  - npm install karma-phantomjs-launcher --save-dev
  - webdriver-manager update
  - cd public
  - bower install
  - cd ..
before_script:
  - grunt
  - cd dist
script:
  - karma start config/karma.config.js --single-run --browsers PhantomJS
